backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/img/"
publish_mode: editorial_workflow
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog/writing" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Feature", name: "featured_image", widget: "boolean", required: false, default: false }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumb", widget: "image" }
      - { label: "Featured Image Alt Text", name: "thumbAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work"
    label: "Portfolio"
    folder: "src/blog/work"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Feature", name: "featured_image", widget: "boolean", required: false, default: false }
      - { label: "Position", name: "position", widget: "string", required: false, default: false }
      - { label: "Start Date", name: "start_date", widget: "datetime", required: false, default: "", date_format: "MMM YYYY" }
      - { label: "End Date", name: "end_date", widget: "datetime", required: false, default: "", date_format: "MMM YYYY" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumb", widget: "image" }
      - { label: "Featured Image Alt Text", name: "thumbAlt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }